name: Compilation & tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  nanos-build:
    name: Build app for NanoS
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Build
        run: make
      - name: Upload app binary
        uses: actions/upload-artifact@v2
        with:
          name: nanos-app
          path: bin

  nanox-build:
    name: Build app for NanoX
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Build
        run: |
          make BOLOS_SDK=$NANOX_SDK
      - name: Upload app binary
        uses: actions/upload-artifact@v2
        with:
          name: nanox-app
          path: bin

  nanosp-build:
    name: Build app for NanoS+
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Build
        run: |
          make BOLOS_SDK=$NANOSP_SDK
      - name: Upload app binary
        uses: actions/upload-artifact@v2
        with:
          name: nanosp-app
          path: bin

  scan_build:
    name: Clang Static Analyzer
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Clang Static Analyzer
        run: |
          make clean
          scan-build --use-cc=clang -analyze-headers -enable-checker security -enable-checker unix -enable-checker valist -o scan-build --status-bugs make default
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: scan-build
          path: scan-build
